default:
  image: node:lts
  before_script:
    - npm install

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - npm test

pages:
  stage: deploy
  script:
    - cp -r docs public
  artifacts:
    paths:
      - public
  only:
    - master
